version: "3.0"

services:
  exchange_microservice:
    build: ./sf-academy-exchange-microservice
    ports:
      - 9000:9000

  user_microservice:
    build: ./sf-academy-user-microservice
    depends_on:
      - exchange_microservice
      - user_db
    env_file: ./sf-academy-user-microservice/.env
    ports:
      - 9001:9001

  api_server:
    build: ./sf-academy-api
    depends_on:
      - exchange_microservice
      - user_microservice
    env_file: ./sf-academy-api/.env
    ports:
      - 3000:3000

  webapp_server:
    build: ./sf-academy-webapp
    depends_on:
      - api_server
    ports:
      - 8080:3000
    volumes:
      - ./sf-academy-webapp/pages:/usr/src/app/pages
      - ./sf-academy-webapp/components:/usr/src/app/components
      - ./sf-academy-webapp/public:/usr/src/app/public

  nginx_server:
    build: ./sf-academy-nginx
    depends_on:
      - api_server
    restart: always
    ports:
      - 80:80

  user_db:
    build: ./sf-academy-user-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sf_academy_exchange_db
    ports:
      - 3306:3306
